
# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="audio.mp3"
Content-Type: audio/mpeg

< ./audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/652644ba-7b8f-4220-94a3-48f5669368a9/transcription
Content-type: application/json

{
    "prompt": "planeta terra"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-type: application/json

{
    "videoId": "652644ba-7b8f-4220-94a3-48f5669368a9",
    "temperature": 0.5,
    "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: ```{transcription}```"
}